# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68b7d79390555cfccd5da3d51973b8aa0cb1d57c48cbd91985badc9a289e305ee37e6add3d88087f34d09db0126ec8dc918921371c61f5e05d69bfd7bb1c43a2
  google_maps_api_key: <%= ENV.fetch 'GOOGLE_MAPS_API_KEY' %>

test:
  secret_key_base: 661fcb33264944ae70abde8cc28d117f285852ba8042bc4ccd98a34b6b5cbce8349c614af877e689ac59ec9c7b226480f276196d44901ef3b729052b589aeabb
  google_maps_api_key: <%= ENV.fetch 'GOOGLE_MAPS_API_KEY' %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base:     <%= ENV["SECRET_KEY_BASE"] %>
  google_maps_api_key: <%= ENV.fetch 'GOOGLE_MAPS_API_KEY' %>
